# Generated by Django 5.2.8 on 2025-11-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(help_text='Original CSV file name', max_length=255)),
                ('file_path', models.CharField(blank=True, help_text='S3 file path', max_length=500, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_records', models.IntegerField(default=0, help_text='Total records in CSV')),
                ('processed_records', models.IntegerField(default=0, help_text='Number of records processed')),
                ('successful_records', models.IntegerField(default=0, help_text='Successfully imported records')),
                ('failed_records', models.IntegerField(default=0, help_text='Failed to import records')),
                ('error_message', models.TextField(blank=True, help_text='Error details if failed', null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Upload History',
                'verbose_name_plural': 'Upload Histories',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Webhook endpoint URL', max_length=500)),
                ('event_type', models.CharField(choices=[('product_created', 'Product Created'), ('product_updated', 'Product Updated'), ('product_deleted', 'Product Deleted'), ('bulk_upload_complete', 'Bulk Upload Complete'), ('bulk_delete_complete', 'Bulk Delete Complete')], help_text='Event that triggers this webhook', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Enable or disable webhook')),
                ('description', models.TextField(blank=True, help_text='Webhook description', null=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('last_response_code', models.IntegerField(blank=True, help_text='Last HTTP response code', null=True)),
                ('last_response_time', models.FloatField(blank=True, help_text='Last response time in seconds', null=True)),
                ('retry_count', models.IntegerField(default=3, help_text='Number of retry attempts on failure')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Webhook',
                'verbose_name_plural': 'Webhooks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, help_text='Stock Keeping Unit - unique identifier (case-insensitive)', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Product name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Product description', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the product is active or inactive')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sku'], name='product_pro_sku_34f508_idx'), models.Index(fields=['name'], name='product_pro_name_b60cd1_idx'), models.Index(fields=['is_active'], name='product_pro_is_acti_9d034c_idx')],
            },
        ),
    ]
