# Generated by Django 5.2.8 on 2025-11-14 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='event_type',
            field=models.CharField(choices=[('bulk_upload_complete', 'Bulk Upload Complete'), ('bulk_upload_failed', 'Bulk Upload Failed'), ('bulk_delete_complete', 'Bulk Delete Complete')], help_text='Event that triggers this webhook', max_length=50),
        ),
    ]
